import { readFileSync } from 'node:fs';
const src = readFileSync(new URL('../src/handlers/stripe.js', import.meta.url),'utf8');
const body = src.slice(src.indexOf('const asId ='), src.indexOf('function getPaymentIntentIdFromCharge'));
const get = new Function(`${body}; return getPaymentIntentIdFromInvoice;`)();
let p=0,t=0; const ck=(n,a,e)=>{t++; if(a===e){p++;console.log(`  PASS  ${n}`)} else console.log(`  FAIL  ${n}: expected "${e}", got "${a}"`)};

ck('classic: payment_intent as string', get({payment_intent:'pi_A'}), 'pi_A');
ck('classic: payment_intent expanded', get({payment_intent:{id:'pi_B'}}), 'pi_B');
ck('expanded charge', get({charge:{payment_intent:'pi_C'}}), 'pi_C');
ck('expanded charge, nested', get({charge:{payment_intent:{id:'pi_D'}}}), 'pi_D');
ck('Invoice Payments API 2025', get({payments:{data:[{payment:{payment_intent:'pi_E'}}]}}), 'pi_E');
ck('Invoice Payments without wrapper', get({payments:{data:[{payment_intent:'pi_F'}]}}), 'pi_F');
ck('nested under payment_details', get({payments:{data:[{payment:{payment_details:{payment_intent:'pi_G'}}}]}}), 'pi_G');
ck('inside lines[]', get({lines:{data:[{payment_intent:'pi_H'}]}}), 'pi_H');
ck('real 13 Aug payload (none present)', get({id:'in_1',customer:'cus_1',amount_paid:418,currency:'usd'}), '');
ck('charge as string does not invent a PI', get({charge:'ch_X'}), '');
ck('empty object', get({}), '');
ck('null fields', get({payment_intent:null,charge:null,payments:null,lines:null}), '');
ck('empty payments', get({payments:{data:[]}}), '');
ck('precedence: direct field wins', get({payment_intent:'pi_TOP',payments:{data:[{payment:{payment_intent:'pi_LOW'}}]}}), 'pi_TOP');
console.log(`\n${p}/${t} checks passed`); if(p!==t) process.exitCode=1;
